#!/usr/bin/env bash
# 101-manage_my_process
#  manages manage_my_process.



if [[ "$1" == "start" ]]
then
    if [ -f /var/run/my_process.pid ]
    then
        echo "manage_my_process is already running."
    else
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
    fi
elif [[ "$1" == "stop" ]]
then
    if [ -f /var/run/my_process.pid ]
    then
        PID=$(cat /var/run/my_process.pid)
        kill $PID
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
elif [[ "$1" == "restart" ]]
then
    if [ -f /var/run/my_process.pid ]
    then
        PID=$(cat /var/run/my_process.pid)
        kill $PID
        rm /var/run/my_process.pid
    fi
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: $0 {start|stop|restart}"
fi
